### ISSUE TITLE
Content response for DELETE request

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-rest#9]
Would like to have content responses for a DELETE requests.  Currently returns 204 (No Content) status code.

``` php
public function delete($id) {
    return true;
    // Would like to return a response like below on success..
    // return array('status' => 'deleted', 'id' => $id);
}
```

---

Originally posted by @friendofpa at https://github.com/zfcampus/zf-rest/issues/58

**Comment by weierophinney** [comment]
From http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

> A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.

So the developer should have the freedom of return an object.


---

Originally posted by @Maks3w at https://github.com/zfcampus/zf-rest/issues/58#issuecomment-78355007

**Comment by burgermister** [comment]
```
public function delete($id) {
    $response = new Laminas\Http\Response();
    $response->setStatusCode(Laminas\Http\Response::STATUS_CODE_200);
    $response->setContent('Item deleted successfully');
    return $response;
}
```

**Comment by Ocramius** [comment]
Closing as "won't fix" here.
